### ISSUE TITLE
not running on nvidia gpu by default / not corrrectly displaying ui elements when forced to (wayland/ nvidia intel optimus)

### ISSUE THREAD

**Issue by porcupinecoder** [flathub/info.beyondallreason.bar#20]
opensuse tw, kde wayland. intel/nvidia optimus laptop. nvidia gpu enabled via `sudo prime-select nvidia`

game would not use nvidia gpu. solved using flatseal + these env variables: `__NV_PRIME_RENDER_OFFLOAD=1` and `__GLX_VENDOR_LIBRARY_NAME=nvidia`

however, using these variables, the launcher graphical elements will not load, it is simply black, but fully interactable. i can launch the game, which runs using discreet nvidia graphics at a smooth fps, but menu UI flickers occasionally, and certain UI elements in-game are missing (text in the bottom right that keeps track of players, meny text in the top right, sometimes the icons for faction selection + a lot more)

**Comment by tobias47n9e** [comment]
About the launcher: It uses electron 11 (https://github.com/beyond-all-reason/spring-launcher/blob/master/package.json#L63). I think good Wayland support was implemented in later versions.

It's odd that the game did not default to the NVIDIA GPU. I actually I thought the line `PrefersNonDefaultGPU=true` (https://github.com/flathub/info.beyondallreason.bar/blob/master/info.beyondallreason.bar.desktop#L10) should take care of that.

The flickering sounds like a third problem, which is probably related to the engine. You could check the issues here, or create a new one: https://github.com/beyond-all-reason/Beyond-All-Reason/issues

**Comment by p2004a** [comment]
I'm going to closet this as obsolete, I've not seen any support issues about this on BAR discord for quite a while.
