### ISSUE TITLE
Add new contributors

### ISSUE THREAD

**Issue by tobias47n9e** [flathub/info.beyondallreason.bar#5]
@hfiguiere Can you add @Born2Crawl as a maintainer for this repo?

**Comment by hfiguiere** [comment]
I can't I don't have permissions for that. However @barthalion can.

**Comment by barthalion** [comment]
Sorry, this got lost in my inbox. Sent an invite to @Born2Crawl.

**Comment by Born2Crawl** [comment]
No worries, thanks a lot!

**Comment by tobias47n9e** [comment]
Thanks
