### ISSUE TITLE
Environment override needed for Wayland

### ISSUE THREAD

**Issue by JordanL2** [flathub/info.beyondallreason.bar#8]
On Wayland I needed to add this environment override (because GDK_BACKEND is set to "wayland"):

```
flatpak --user override --env=GDK_BACKEND=x11 info.beyondallreason.bar
```

It might be best to add that override to the manifest?

**Comment by tobias47n9e** [comment]
@JordanL2 I am mostly using the Wayland session of Ubuntu 21.10 and don't need any override. Can you give some details about your setup? That would help me test the issue and the proposed fix. Thanks

**Comment by JordanL2** [comment]
I expect the difference is I'm explicitly setting the environment variable GDK_BACKEND to "wayland".

(It's possible I shouldn't be doing this and GTK will default to Wayland anyway - Firefox needs it but that can be forced to use Wayland with the MOZ_ENABLE_WAYLAND variable.)

**Comment by tobias47n9e** [comment]
@JordanL2 Did you resolve the issue with `MOZ_ENABLE_WAYLAND`?

I for example use this line in `.bashrc` to start the Wayland session of Firefox:

```
alias firefox-wayland="GDK_BACKEND=wayland firefox"
```

I am still not sure what the distros recommend in this case, when an application can only launch with x11-backend. Are there distros that have `GDK_BACKEND=wayland` set by default?

**Comment by JordanL2** [comment]
Yes you're right, unsetting `GDK_BACKEND` and only using `MOZ_ENABLE_WAYLAND` works for all apps.
